services:
  backend:
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - SYSTEM_LANGUAGE=${SYSTEM_LANGUAGE}

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
